services:
  - type: web
    name: safe_legal_ai
    runtime: python
    pythonVersion: 3.10.13
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn corrected_v2_final3_safe_clause:app --host 0.0.0.0 --port 10000
